#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
spec="${AXTP_SPEC_PATH:-$root/third_party/axtp-spec}"

if [[ ! -d "$spec/registry" ]]; then
  echo "AXTP_SPEC_PATH must point to an AXTP spec checkout with registry/." >&2
  echo "Current value: $spec" >&2
  exit 1
fi

if [[ ! -f "$root/generators/dist/sourceLoader.js" ]]; then
  echo "Generator is not built. Run: pnpm --dir generators build" >&2
  exit 1
fi

AXTP_RUNTIME_ROOT="$root" AXTP_SPEC_ROOT="$spec" node --input-type=module <<'NODE'
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

const root = process.env.AXTP_RUNTIME_ROOT;
const specRoot = process.env.AXTP_SPEC_ROOT;

const { loadProtocolSources } = await import(pathToFileURL(path.join(root, "generators/dist/sourceLoader.js")).href);
const { validateSpec } = await import(pathToFileURL(path.join(root, "generators/dist/validator.js")).href);

const spec = await loadProtocolSources(specRoot);
for (const message of validateSpec(spec)) console.log(message);

const outDir = path.join(root, "src/axtp_runtime/generated");
await mkdir(outDir, { recursive: true });

const reserved = new Set([
  "False", "None", "True", "and", "as", "assert", "async", "await", "break",
  "class", "continue", "def", "del", "elif", "else", "except", "finally",
  "for", "from", "global", "if", "import", "in", "is", "lambda", "nonlocal",
  "not", "or", "pass", "raise", "return", "try", "while", "with", "yield"
]);

function pyName(name) {
  const value = name
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => {
      const normalized = part === part.toUpperCase() ? part.toLowerCase() : part;
      return normalized.charAt(0).toUpperCase() + normalized.slice(1);
    })
    .join("");
  const safe = value.length > 0 ? value : "Unknown";
  return reserved.has(safe) ? `${safe}_` : safe;
}

function snakeName(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase();
}

function hex(id, width = 4) {
  return `0x${id.toString(16).toUpperCase().padStart(width, "0")}`;
}

function enumBlock(name, items, width) {
  return [...items]
    .sort((lhs, rhs) => lhs.id - rhs.id)
    .map((item) => `    ${pyName(item.name)} = ${hex(item.id, width)}`)
    .join("\n");
}

const ids = `# Generated by axtp-python-runtime generator. Do not edit manually.
from enum import IntEnum


class PayloadType(IntEnum):
${enumBlock("PayloadType", spec.payloadTypes, 2)}


class ControlOpcode(IntEnum):
${enumBlock("ControlOpcode", spec.controlOpcodes, 2)}


class RpcEncoding(IntEnum):
${enumBlock("RpcEncoding", spec.rpcEncodings, 2)}


class RpcBodyEncoding(IntEnum):
${enumBlock("RpcBodyEncoding", spec.rpcBodyEncodings, 2)}


class RpcOp(IntEnum):
${enumBlock("RpcOp", spec.rpcOps, 2)}


class MethodId(IntEnum):
${enumBlock("MethodId", spec.methods, 4)}


class EventId(IntEnum):
${enumBlock("EventId", spec.events, 4)}


class ErrorCode(IntEnum):
${enumBlock("ErrorCode", spec.errors, 4)}


class CapabilityId(IntEnum):
${enumBlock("CapabilityId", spec.capabilities, 4)}
`;

const methodRows = [...spec.methods]
  .sort((lhs, rhs) => lhs.id - rhs.id)
  .map((item) => `    MethodDescriptor(${hex(item.id)}, ${JSON.stringify(item.name)}, ${JSON.stringify(item.domain)}, ${JSON.stringify(item.requestSchema)}, ${JSON.stringify(item.responseSchema)}),`)
  .join("\n");
const eventRows = [...spec.events]
  .sort((lhs, rhs) => lhs.id - rhs.id)
  .map((item) => `    EventDescriptor(${hex(item.id)}, ${JSON.stringify(item.name)}, ${JSON.stringify(item.domain)}, ${JSON.stringify(item.eventSchema)}),`)
  .join("\n");
const errorRows = [...spec.errors]
  .sort((lhs, rhs) => lhs.id - rhs.id)
  .map((item) => `    ErrorDescriptor(${hex(item.id)}, ${JSON.stringify(item.name)}, ${JSON.stringify(item.domain)}, ${Boolean(item.retryable) ? "True" : "False"}),`)
  .join("\n");
const capabilityRows = [...spec.capabilities]
  .sort((lhs, rhs) => lhs.id - rhs.id)
  .map((item) => `    CapabilityDescriptor(${hex(item.id)}, ${JSON.stringify(item.name)}, ${JSON.stringify(item.domain)}, ${JSON.stringify(item.type ?? "")}, ${JSON.stringify(item.schema ?? "")}),`)
  .join("\n");

const registry = `# Generated by axtp-python-runtime generator. Do not edit manually.
from dataclasses import dataclass
from typing import Dict, List, Optional, Sequence, Union

from .axtp_ids_generated import ErrorCode


@dataclass(frozen=True)
class MethodDescriptor:
    id: int
    name: str
    domain: str
    request_schema: str
    response_schema: str


@dataclass(frozen=True)
class EventDescriptor:
    id: int
    name: str
    domain: str
    event_schema: str


@dataclass(frozen=True)
class ErrorDescriptor:
    id: int
    name: str
    domain: str
    retryable: bool


@dataclass(frozen=True)
class CapabilityDescriptor:
    id: int
    name: str
    domain: str
    type: str
    schema: str


K_METHOD_REGISTRY: Sequence[MethodDescriptor] = (
${methodRows}
)

K_EVENT_REGISTRY: Sequence[EventDescriptor] = (
${eventRows}
)

K_ERROR_REGISTRY: Sequence[ErrorDescriptor] = (
${errorRows}
)

K_CAPABILITY_REGISTRY: Sequence[CapabilityDescriptor] = (
${capabilityRows}
)


class RegistryLookup:
    @staticmethod
    def method_id_by_name(name: str) -> Optional[int]:
        for descriptor in K_METHOD_REGISTRY:
            if descriptor.name == name:
                return descriptor.id
        return None

    @staticmethod
    def method_by_id(method_id: int) -> Optional[MethodDescriptor]:
        for descriptor in K_METHOD_REGISTRY:
            if descriptor.id == method_id:
                return descriptor
        return None

    @staticmethod
    def event_id_by_name(name: str) -> Optional[int]:
        for descriptor in K_EVENT_REGISTRY:
            if descriptor.name == name:
                return descriptor.id
        return None

    @staticmethod
    def event_by_id(event_id: int) -> Optional[EventDescriptor]:
        for descriptor in K_EVENT_REGISTRY:
            if descriptor.id == event_id:
                return descriptor
        return None

    @staticmethod
    def error_by_code(code: Union[ErrorCode, int]) -> Optional[ErrorDescriptor]:
        value = int(code)
        for descriptor in K_ERROR_REGISTRY:
            if descriptor.id == value:
                return descriptor
        return None


@dataclass(frozen=True)
class MethodRegistryEntry:
    id: int
    name: str


class MethodRegistry:
    def __init__(self) -> None:
        self._name_to_id: Dict[str, int] = {}
        self._id_to_name: Dict[int, str] = {}

    @classmethod
    def from_generated_defaults(cls) -> "MethodRegistry":
        registry = cls()
        for method in K_METHOD_REGISTRY:
            registry.add_method(method.id, method.name)
        return registry

    def add_method(self, method_id: int, method_name: str) -> None:
        existing_name = self._id_to_name.get(method_id)
        if existing_name is not None:
            self._name_to_id.pop(existing_name, None)
        existing_id = self._name_to_id.get(method_name)
        if existing_id is not None:
            self._id_to_name.pop(existing_id, None)
        self._name_to_id[method_name] = method_id
        self._id_to_name[method_id] = method_name

    def find_method_id(self, method_name: str) -> Optional[int]:
        return self._name_to_id.get(method_name)

    def find_method_name(self, method_id: int) -> Optional[str]:
        return self._id_to_name.get(method_id)

    def contains_method(self, method: Union[int, str]) -> bool:
        if isinstance(method, int):
            return method in self._id_to_name
        return method in self._name_to_id

    def entries(self) -> List[MethodRegistryEntry]:
        return [
            MethodRegistryEntry(method_id, name)
            for method_id, name in sorted(self._id_to_name.items())
        ]
`;

await writeFile(path.join(outDir, "__init__.py"), "from .axtp_ids_generated import *\nfrom .registry import *\n");
await writeFile(path.join(outDir, "axtp_ids_generated.py"), ids);
await writeFile(path.join(outDir, "registry.py"), registry);
console.log(`[OK] generated Python artifacts: ${outDir}`);
NODE

AXTP_SPEC_PATH="$spec" node "$root/scripts/axtp-versioning.mjs" generate --runtime-name axtp-python-runtime
